### ISSUE TITLE
Loop associations produce invalid included relationships

### ISSUE THREAD

**Issue by dynamiccast** [danivek/json-api-serializer#10]
Hi,

Once again, thanks for this great module !
Today, I encountered a tricky use case.
I have the following many to many relationship:

````
Pets have many homes (of type Houses)
Houses have many pets (of type Pets)
````

When I try to serialize the following : 

````
Serializer.serialize("pets", {
    "homes": [{
        "city": "Paris",
        "id": 2
    }],
    "name": "Dushi",
    "color": "white",
    "id": 2
});
````

I have this result:

````
{
    "data": {
        "type": "pets",
        "id": "2",
        "attributes": {
            "name": "Dushi",
            "color": "white"
        },
        "relationships": {
            "homes": {
                "data": [{
                    "type": "houses",
                    "id": "2"
                }]
            }
        }
    },
    "included": [{
        "type": "houses",
        "id": "2",
        "attributes": {
            "city": "Paris"
        },
        "relationships": {
            "pets": {
                "data": []
            }
        }
    }]
}
````

The problem is the `data` record defines a relationship with `Houses` (via `homes`), but the *included* `Houses` defines no relationships with `Pets`.

This means depending on where the piece of code receiving the serialized json is looking for a relationship, there is a chance it misses the association between `Pets` with id `2` and `Houses` with id `2`.
By the way, this is the case with Ember.js which is a frontend framework expecting to work with a JSON API compliant backend by default.

The correct output JSON would be:

````
{
    "data": {
        "type": "pets",
        "id": "2",
        "attributes": {
            "name": "Dushi",
            "color": "white"
        },
        "relationships": {
            "homes": {
                "data": [{
                    "type": "houses",
                    "id": "2"
                }]
            }
        }
    },
    "included": [{
        "type": "houses",
        "id": "2",
        "attributes": {
            "city": "Paris"
        },
        "relationships": {
            "pets": {
                "data": [{
                    "type": "pets",
                    "id": "2"
                }]
            }
        }
    }]
}
````

What do you think ?

**Comment by danivek** [comment]
Hi @dynamiccast,

What your input data looks like ? You should have too much recursive inclusion ?

**Comment by dynamiccast** [comment]
The input data is:

````
{
    "homes": [{
        "city": "Paris",
        "id": 2
    }],
    "name": "Dushi",
    "color": "white",
    "id": 2
}
````

Actually, there is only one level or recursion. It's just that being a *many to many* type of relationship, it should go both ways.

**Comment by dynamiccast** [comment]
The input data is:

````
{
    "homes": [{
        "city": "Paris",
        "id": 2
    }],
    "name": "Dushi",
    "color": "white",
    "id": 2
}
````

It works fine because it includes an `House` which is defined by the `homes` association. But why is the included record being defined an empty relationship with `Pets` ?

I would have expect the included record not to mention relationships which it has no information about instead of defining `House` not to be related with any `Pets`.

**Comment by danivek** [comment]
I think you have define a relationship option with ```Pets``` on the ```Houses``` schema, and your input data via ```homes``` have no relationship data expected for ```pets```. It should be at least unpopulated relationship (id or array of id) or the complete data of ```pets``` to be serialized like this : 

```
"relationships": {
  "pets": {
     "data": [{
       "type": "pets",
         "id": "2"
       }]
   }
}
````

Your relationship here (```Pets``` on the ```Houses```) appears to be empty in your input data, and it follows this [JSONAPI convention](http://jsonapi.org/format/#document-resource-object-linkage).

> Resource linkage MUST be represented as one of the following:
> - null for empty to-one relationships.
> - an empty array ([]) for empty to-many relationships.
> - a single resource identifier object for non-empty to-one relationships.
> - an array of resource identifier objects for non-empty to-many relationships.

**Comment by danivek** [comment]
If you expect the included record not to mention relationships which it has no information about it in your input data, you can use a [custom schema](https://github.com/danivek/json-api-serializer#custom-schemas).

A custom schema with default options and without any relationship option :
```Serializer.register('houses', 'noPetsRelationship', {});```

And on the ```houses``` relationship on the ```pets``` resource :
```
Serializer.register('pets', {
 relationships: {
   homes: {
   type: 'houses'
   schema: 'noPetsRelationship'
   }
 }
});

```

**Comment by dynamiccast** [comment]
Ok, you are right. I understand your point now.
I indeed registered both resources to have an association between each other but did mention the relationship only for `Pets->Houses` and not `Houses->pets`.

Thank you for the custom schema idea.
I will have to figure out how to implement it in my module. Currently, on program startup, I just scan for all Models defined to my ORM and registered all resources with their associations.
I guess I will have to customize this a little bit so it adapts to the output from my ORM.
