### ISSUE TITLE
ObjectID (mongodb) should be serialized with .toString() and not treated as an object

### ISSUE THREAD

**Issue by c-dima** [danivek/json-api-serializer#100]
ObjectIDs should be automatically serialized as strings and not treated as nested objects or better, add an option to specify which field should be serialized with String or more generic, a custom function.

Currently, I'm using a dedicated middleware to stringify the ObjectIDs before serializing the data, but this is overkill.

**Comment by danivek** [comment]
json-api-serializer apply a `toString()` on `id` field https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L585

Do you mean that you have another field with an ObjectID that is not declared as an "id"?

**Comment by danivek** [comment]
closed due to inactivity, feel free to reopen this issue if needed.
