### ISSUE TITLE
Would you be interested in a conversion to Typescript? 

### ISSUE THREAD

**Issue by Kristof-Mattei** [danivek/json-api-serializer#109]
@danivek ^

Happy to help out with this. 

We would need a couple of things:

* the conversion, which I would help with / do completely on my own
* a build process, as we then cannot just 'include' the result of a git clone as a package

**Comment by jun-sheaf** [comment]
I have developed a full-featured library in typescript for simply serializing JSON:API. It serializes the entire spec.

Link: [https://github.com/jun-sheaf/ts-japi](https://github.com/jun-sheaf/ts-japi)

**Comment by Istanful** [comment]
@Kristof-Mattei I also don't know if this is interested for the author. I'm using this library for my project and thus needed the type definitions.

I created a pull request to DefinitelyTyped. When it is merged types can be installed with `npm install @types/json-api-serializer`.

In the meantime if you need the types you can copy them from this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52110

(You would then need to add them in a .d.ts file)

**Comment by danivek** [comment]
See issue #60
