### ISSUE TITLE
ValidationError: beforeSerialize is not allowed

### ISSUE THREAD

**Issue by nrcmkoh** [danivek/json-api-serializer#114]
I'm seeing this error when try to set up a composite `id`:
`ValidationError: beforeSerialize is not allowed`

Here's my code to register the types. Note that I am not getting an error to serialize the other relationship `locationGoals`, which doesn't use `beforeSerialize()`:
```ts
      serializer.register('client', {
        id: 'id',
        relationships: {
          alertingAccesses: { type: 'alerting-accesses' },
          locationGoals: { type: 'location-goals' },
        },
      });

      serializer.register('alerting-accesses', {
        beforeSerialize: (data) => {
          return { ...data, id: `${data.realtimeUserId}_${data.clientId}` };
        },
      });

      serializer.register('location-goals', {
        id: 'id',
      });
```

I've used `beforeSerialize()` on other occasions without running into this error, so I'm not sure why it's happening here.

json-api-serializer version: 2.5.0

**Comment by danivek** [comment]
`ValidationError` comes from the` joi` package which was used on version lower than 2.0.0.
As of 2.0.0 it no longer uses `joi`, so you shouldn't get this error.

Please check your version of `json-api-serializer`

**Comment by nrcmkoh** [comment]
It looks like I had a stale version of this package in my `node_modules` folder because my `package.json` has this in it:
![image](https://user-images.githubusercontent.com/20341524/89911908-d30b2b00-dba6-11ea-99b8-12f240f27a3f.png)

I manually removed the package and ran `npm install`, and everything appears to be working now. Thanks!
