### ISSUE TITLE
Unintended object in attributes

### ISSUE THREAD

**Issue by shankiflang** [danivek/json-api-serializer#122]
Hello,

I currently have this code in my serializer :
`
export default {
	jsonapiObject: false,
	id: 'id',
	links: {
		self: function (data) {
			return '/v1/ingredients/' + data.id
		},
	},
}
`
that returns lots of data in attrtibutes like in code bellow. Is there any way to return only the basic attributes?
`     
{
  "data": [
    {
      "type": "ingredients",
      "id": "6082d2ff72de5a0cb0e08a42",
      "attributes": {   
                    "$__": {}
                    "isNew": false,
                    "$locals": {},
                    "$op": null,
                    "_doc": {
                              "_id": "6082d2ff72de5a0cb0e08a42",
                              "name": "XXX",
                              "category": "XXX"
                    },
                    "$init": true
       },
      "links": {
        "self": "/v1/ingredients/6082d2ff72de5a0cb0e08a42"
      }
    }
  ]
}
`

**Comment by danivek** [comment]
@shankiflang I think you are working with an ORM object (seems to be a mongoose Document in your exemple).

It will work better if you call `.toJSON()` or `.toObject()` before passing it to the serializer.

**Comment by shankiflang** [comment]
@danivek I just added a .lean() at the end of my .find() and it seems to have fixed the problem. Thanks for your help.
