### ISSUE TITLE
Is there an option to remove undefined properties?

### ISSUE THREAD

**Issue by yidongw** [danivek/json-api-serializer#127]
It is too verbose to have those properties undefined. Can we have an option to remove all those fields?

`JSON.parse(JSON.stringify(object))` should be able to handle that

**Comment by danivek** [comment]
Seems to be related to #53

Actually there is no option to do that. The only way is using `JSON.stringify` to strip `undefined` data.  it's the standard way of preparing JSON-payloads for responses or requests in many NodeJS frameworks and I don't see a need to add the handling of these values to this serializer again
