### ISSUE TITLE
deserialize Included block

### ISSUE THREAD

**Issue by ungrim97** [danivek/json-api-serializer#17]
Hi,

So far this library has been fantastically useful. However...

Unless I have misread something, I don't believe JSONAPISerializer.deserialize(type, data) will do anything with the included resources.

I think it should be possible to deserialize the included resources first and then pass those in to deserializeRelationships and set that on the deserializedData[relationshipKey].

If this is something that sounds sane I will try and put together a PR with the above change.

Thanks.

**Comment by danivek** [comment]
Hi @ungrim97,

You are right, actually deserialize function do nothing with the included resources.
I actually use this library on server side only, so I never needed to deserialize these included resources.

It would be great if the deserialize function can do it. 
I will investigate further on how to do it.

a PR is welcome, Thanks.

**Comment by ungrim97** [comment]
@danivek Cheers for the response. We are using it server side as well but have some POST/PUT requests from Ember Data that have included resources that need to be deserialised. Currently we do this manually.

Will try and find time to put a PR together.

**Comment by danivek** [comment]
@ungrim97 As you use it on server side,  and according to the JSONAPI specification, on creating or updating a resource, the spec says nothing about ```included``` key on input data. 
Also PUT method is not allowed by the spec.

I am surprised that Ember uses it like this.

Also, it could be great to have this feature for client side deserialization purposes. So why not...

**Comment by danivek** [comment]
@ungrim97, I made a try on branch [deserialize-included](https://github.com/danivek/json-api-serializer/tree/deserialize-included)

Please tell me if it correspond to your need

Thanks

**Comment by danivek** [comment]
@ungrim97 Any feedback ?

**Comment by ungrim97** [comment]
Sorry @danivek work has been crazy. This looks perfect but I have only tested with direct included (included resources for the primary resource, not included resources for any included resources)

**Comment by danivek** [comment]
No problem @ungrim97, I know that. Good catch, I modify my test to also test the second case (included resources for any included resources)

Thanks
