### ISSUE TITLE
Adding async serialization to avoid blocking

### ISSUE THREAD

**Issue by mattii** [danivek/json-api-serializer#18]
Hi @danivek!

I really like the flexibility of *json-api-serializer* and it helped us a lot to add json-api capabilities to our rest-api. But we experienced some serious performance issues on large response-payloads, as the serialization is synchronous and thus blocking the loop for several seconds (depending on the payload-size). For small payloads this is not a real issue, and of course, we could optimize on our side by paginating large requests and thus dividing the long blocking process in several smaller blocking processes. But sometimes it can be very handy to have everything in one request…

What do you think about adding an async interface by returning a promise? To avoid adding breaking changes, we could add another method like `Serializer.serializeAsync()`.

To convert it to a non-blocking operation we could serialize every item of a data-array with a `nextTick`? Or convert the array to a stream and process this stream until returning the processed payload as promise?

I would like to add this functionality and add a PR, but let's discuss how the API should look like before.

**Comment by danivek** [comment]
Hi @mattii,

I had already thought about adding non blocking code because of performance issues on large payloads, but I have absolutely no idea on how to do that. I know that we can use nextTick or stream, but i never did that.

According to you, wich is the best between ```process.nextTick``` and stream ? maybe both ?
How it work if you use these features on browser ?

I agree to not break compatibility and add method like ```Serializer.serializeAsync()```.

I will investigate further on best practices for non-blocking code. 
If you know how to do that, I am pleased that we can work together on a PR.

Thanks @mattii

**Comment by mattii** [comment]
Great! Sure, let's work together on this feature.

We could use something like https://github.com/sindresorhus/into-stream to convert the data-array into a stream. It pushes an array-item into the stream on each tick (via `setImmediate`). Now we only need to read this stream and serialize every array-item as it comes, forming the json-api payload step by step. When the stream ends, we just resolve a promise with the completed payload.

If you want, I can start with an implementation next week.

Regarding browser compatibility: this could be difficult. I think browsers don't support `setImmediate` and I'm not sure about streams there either. Is this a requirement you have for this module? Then we might need to research on that area before.

**Comment by danivek** [comment]
Personnally I don't use it on client side, and browser compatibility was not my first intention when I make this library. So it's not a requirement actually.

**Comment by danivek** [comment]
@mattii 

I made a quick try, and it work very well on medium payload (<5000). Execution time take 
2x less time at least. But on large payload (10000 object) there is no significant difference on execution time... 

Maybe this line https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L260 is in cause, included array grows and maybe the uniqWith function take too much time.

**Comment by mattii** [comment]
Fine! We could add a note to the README to clarify that it is a node-module and not tested for browsers.

**Comment by mattii** [comment]
Sorry, did not read your last comment. I guess doing the serialization async with a stream won't make it faster, but it won't block the loop. If the synchronous serialization takes 10 seconds now, the complete node process is blocked and not able to process any other request, producing 5xx responses...
