### ISSUE TITLE
Ignore if missing

### ISSUE THREAD

**Issue by karellm** [danivek/json-api-serializer#25]
I was wondering if you'd be interested in adding an option to skip that `data` attribute in relationships if it is missing.

If a school has many students. When I return the school, I want the `links` to get the students to be included but not the actual data.

```
// school
{
  id: 1,
  name: 'bla'
  // no students here
}
```

```
{
  data: {
    attributes: [],
    id: 1,
    type: 'schools',
    relationships: {
      students: {
        data: null, // I don't want that
        links: {}
      }
    }
  }
}
```
Something like:

```
Serializer.register('school', {
  id: 'id',
  relationships: {
    students: {
      type: 'student',
      skipDataIfMissing: true,
      links: {
        related: (school) => `/schools/${school.id}/students`
      }
    }
  }
});
```

Thanks

**Comment by danivek** [comment]
In the JSON API specification, on “relationships object”, we have the following: 
> null for empty to-one relationships. 
> an empty array ([]) for empty to-many relationships.

See http://jsonapi.org/format/#document-resource-object-linkage for more info.

In my opinion, I think it's better to avoid adding this option, because the outputed data will not be JSON API compliant. And the role of a serializer is to prevent generating non-compliant response.

@mattii  any thoughts ?

**Comment by mattii** [comment]
Yes, I think JSON API compliance should be our goal here. @karellm, could you explain why you don't want to have the data-field included?

**Comment by karellm** [comment]
I'm not familiar with the entire spec and I agree that it is a good idea to follow it. Maybe I'm missing something.

I use Ember.js, and if a relationship as `data: []` or `data: null`, then it removes all the items already associated. That is to be expected. I actually think that it is the proper behaviour. 

Ember also relies on `links` to know how to grab the data. So it is important to include these, otherwise, Ember doesn't know how to get the "school students".

In an application (think optimization), I might want to fetch only the school from the database, without bothering with the students. In that scenario, I would like the serialized payload to include the `links` so it knows where to grab the students if needed but ignore the `data` altogether. I would skip the attribute. I can't have it be `[]` or `null` since it would clear the potentially existing relations in my Ember app. That said, Ember wouldn't do anything if the `data` attribute is not there.

Does it clarify a bit the use case I'm hitting? Does the spec say anything about skipping the `data` attribute? I understand the valid values but that's not my concern here. It is really its presence.

**Comment by mattii** [comment]
Yes, that's a valid use-case. Could you show us the complete source object, that you pass to the serializer?

I have a similar use-case and if I don't define the relationship in my source-object, the relationship will only contain the `links` field (like you need it).

**Comment by karellm** [comment]
I use sequelize so I have little control over the source object. Here is what I can tell you:

```js
const school = await School.findById(1);
school.students // function
school.students() // []
```

Now if I include things:

```js
const school = await School.findById(1, {include: [Student]});
school.students // [{id: 1, name: 'John'}]
```

I don't know if that helps. What I can say is that this would greatly help us in our current application. It allows for some neat optimizations of the db queries.

**Comment by karellm** [comment]
I think that if the relation `students` is on of `null`, `{ ... }` or `[ ... ]` it could be included (even if these are empty. Otherwise it could be skipped (`undefined`, `string`, `function`).

It could either be a default behaviour (I think it is a fair one) or an option `skipDataIfMissing`.

**Comment by mattii** [comment]
What do you pass to the serializer? The `school` object? How does it look?
Maybe it's best if you pass the complete code from fetching the database to serializing the response.

If you don't want the `students` relationship's data-field to be set, then the `students` field in `school` needs to be `undefined`.

**Comment by karellm** [comment]
@mattii The result of `JSON.stringify(school)` in my first example (without the include) doesn't have a `students` key at all, so yes it would be `underfined`:

```json
const school = await School.findById(1);
JSON.stringify(school);
{
  "name": "School Name"
}

const school = await School.findById(1, {include: [Student]});
JSON.stringify(school);
{
  "name": "School Name",
  "students": [
    { "id": 1, "name": "John" }
  ]
}
```
 I'm not familiar with the internal of Sequelize or json-api-serializer so I'm not sure what object you rely one. If you need more informations, let me know.

**Comment by danivek** [comment]
@karellm, I'm not familiar with Ember or Sequelize, but if I correctly understand, you are facing the issue only your first example, without include, right ? 

If so it should be `undefined`. If not, can you post the result of `typeof school.students` on your first example ?

**Comment by danivek** [comment]
@karellm I think you are trying to serialize the Sequelize model instance instead of a JSON object. I take a look at the Sequelize doc, and I think you will have better result with calling `toJSON()` before passing it to the `serialize` method

**Comment by karellm** [comment]
I will summarize everything. But I think I mislead the conversation bringing Sequelize and Ember into the mix. In short if the `students` is undefined, I'd like a way to avoid `data` to be set.

## Without include

```js
const school = await School.findById(1)
typeof school.students // function
school.students() // []
school.toJSON()
{
  "id": "1",
  "name": "School Name"
}
```

## With include

```
const school = await School.findById(1, {include: [Student]})
typeof school.students // object
school.students // [{ "id": 1, "name": "John" }]
school.toJSON()
{
  "id": "1",
  "name": "School Name",
  "students": [
    { "id": 1, "name": "John" }
  ]
}
```

**Comment by danivek** [comment]
I make a simple try with version 1.7.0
```javascript
const JSONAPISerializer = require('json-api-serializer');
var Serializer = new JSONAPISerializer();

// Schools type
Serializer.register('schools', {
  relationships: {
    students: {
      type: 'students',
      links: {
        self: '/students'
      }
    }
  }
});

// Students type
Serializer.register('students');

// Input data for schools
const input = {
  "id": "1",
  "name": "School Name"
};

var output = Serializer.serialize('schools', input);
console.log(JSON.stringify(output, null, 2));
```

output is:

```javascript
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "schools",
    "id": "1",
    "attributes": {
      "name": "School Name"
    },
    "relationships": {
      "students": {
        "links": {
          "self": "/students"
        }
      }
    }
  }
}
```

**Comment by karellm** [comment]
I definitely don't get that result

**Comment by danivek** [comment]
Maybe I repeat myself but I think you try to serialize Sequelize model instance. Try this:
```javascript
const input = school.toJSON();
Serializer.serialize('schools', input);
```
or to be sure (bad practice):
```javascript
const input = JSON.parse(JSON.stringify(school));
Serializer.serialize('schools', input);
```

**Comment by karellm** [comment]
@danivek  Ok so actually `JSON.stringify` strips the undefined values. Try to run this:

```js
const JSONAPISerializer = require('json-api-serializer');
const Serializer = new JSONAPISerializer();

// Schools type
Serializer.register('schools', {
  relationships: {
    students: {
      type: 'students',
      links: {
        self: '/students'
      }
    }
  }
});

// Students type
Serializer.register('students');

// Input data for schools
const input = {
  "id": "1",
  "name": "School Name"
};

const output = Serializer.serialize('schools', input);
console.log(output.data.relationships.students);
```

I get:

```
{ links: { self: '/students' }, data: undefined }
```

This `undefined` is my issue. I can also confirm that whether my output is `school` or `school.toJSON()` doesn't change anything.

**Comment by danivek** [comment]
@karellm Yes, and Ember has a different behavior between `undefined` and non-present property ?

**Comment by mattii** [comment]
Your problem seems not to be related to *json-api-serializer*, but to the way your server formats its responses. I recommend to use `JSON.stringify` for every response, since it produces a valid JSON-string and removes `undefined` values of an object:

```
> console.log(JSON.stringify({ links: { self: '/students' }, data: undefined }, null, 2))
{
  "links": {
    "self": "/students"
  }
}
```
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by karellm** [comment]
@danivek @mattii Thanks for the great help here. I will definitely introduce `JSON.stringify`.
