### ISSUE TITLE
JSON API recommend to use "-" as separator between multiple words

### ISSUE THREAD

**Issue by dynamiccast** [danivek/json-api-serializer#3]
Hi,

While not explicitly required by the spec, JSON API advises that : 

> Member names SHOULD contain only the characters “a-z” (U+0061 to U+007A), “0-9” (U+0030 to U+0039), and the hyphen minus (U+002D HYPHEN-MINUS, “-“) as separator between multiple words.

Source : http://jsonapi.org/recommendations/#naming

*json-api-serializer* treats attributes's keys as they are and do not modify them to follow this recommendation.

I work daily with [Ember.js](http://emberjs.com/) which by default is configured to talk with a JSON API interface. This framework expects multiple words attributes to be separated with a "-". Then when it de-serializes, it gives attributes's keys a camelCase form.

Do you think *json-api-serializer* should follow this recommendation and [decamelize](https://www.npmjs.com/package/decamelize) attributes's key when serializing ?
Or maybe this is the role of the code using this module to provide objects with keys in the format wanted ? Though it is not very convenient to deal with variables containing a dash in Javascript. (Perhaps this is why Ember chose to de-serialize objects to camelCase keys).
If not flexible enough, this could also be an option to pass to the serializer.

Any thoughts ?

**Comment by danivek** [comment]
Hi,

I wanted users to have hands on the input data so I don't make that kind of option. Also I think that for performance reason, it's better to transform the data (dasherize) before using the serializer.

But for more flexible usage of the serializer, I can add an option for it, if you needed it ?

**Comment by dynamiccast** [comment]
In my opinion, such options should be available since it is the recommended format by JSON API.
I would need it because I am considering using *json-api-serializer* in a module I am maintaining : https://github.com/dynamiccast/sails-json-api-blueprints.

It is a module for Sails.js to generate JSON API compliant endpoints. While it is meant to be generic, I primarily focus to support Ember.js as a frontend. Since Ember.js requires multiple word variables to be separated with dashes, I am looking for this kind of behavior.

I have made a Pull Request with the code modification I have done so far : https://github.com/danivek/json-api-serializer/pull/4
It forces this behavior rather than making it optional. Feel free to move from there if you want this feature to be implemented.
