### ISSUE TITLE
Example of a custom schema?

### ISSUE THREAD

**Issue by mcmillhj-wta** [danivek/json-api-serializer#33]
Is there any way an example of a custom schema could be added to the docs? We were hoping to slightly modify the `relationships` key to always return an array of items instead of the current format: 

```
{
	"id": "c82452b7-c3c3-5551-8bef-22a73f9793bb",
	"type": "alerts",
	"attributes": {
		...
	},
	"relationships": {
		"article": {
			"data": {
				"id": "cc19857c-01eb-5c57-b730-be1a05ec54e9",
				"type": "articles"
			}
		}
	}
}
```

to 

```
{
	"id": "c82452b7-c3c3-5551-8bef-22a73f9793bb",
	"type": "alerts",
	"attributes": {
		...
	},
	"relationships": {
		"items": {
			"data": [
                            {
				"id": "cc19857c-01eb-5c57-b730-be1a05ec54e9",
				"type": "articles"
			    }
                       ]
		}
	}
}
```

I know this doesn't match the JSON API schema spec, but it is a simpler format for our client apps to consume.

**Comment by danivek** [comment]
Hi @mcmillhj-wta,

There is an exemple for custom schema in the Usage section on the Readme  (see https://github.com/danivek/json-api-serializer#register-1). It use a custom schema `only-body` for the comment resource.

Even if you use the custom schema feature, you will not be able to do what you expected. You must either transform your input data or transform the serialized output before sending it. 

Why not transform your input data to this before serialize ? (have a property `items` wich is an array):

```
{
  "id": "c82452b7-c3c3-5551-8bef-22a73f9793bb",
    ....
  items: ["cc19857c-01eb-5c57-b730-be1a05ec54e9"]
}
```

with this configuration:
```javascript
Serializer.register('alerts', {
  relationships: {
    items: {
      type: 'articles'
    }
  }
});

Serializer.register('articles', {});
```

**Comment by mcmillhj-wta** [comment]
@danivek Thank you, this was super helpful and I now have it worked as desired.
