### ISSUE TITLE
id not defined by a single column

### ISSUE THREAD

**Issue by chamini2** [danivek/json-api-serializer#37]
I have resources which have id defined by two different columns (composite keys in DB layer). I was wondering if this project would be interested in a PR to make `id` on register to be either a column or a function that returns the id. 

I mean that it could be:

```js
Serializer.register('article', {
  id: 'id', // backwards compatible way of doing it
  relationships: {
    comments: { type: 'comment' }
  }
});

Serializer.comment('comment', {
  id: function(attributes) {
    return `${attributes.user_id},${attributes.article_id}`
  }
});
```

That way it would get data like

```js
Serializer.serialize('article', {
  id: 1,
  title: 'This is json-api-serializer',
  comments: [{
    user_id: 4,
    article_id: 1,
    body: 'OMG, cool project!'
  }, {
    user_id: 6,
    article_id: 1,
    body: 'Yeah, cool project!'
  }]
});
```

Resulting in

```json
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": [{
    "type": "article",
    "id": "1",
    "attributes": {
      "title": "This is json-api-serializer"
    },
    "relationships": {
      "comments": {
        "data": [{
          "type": "comment",
          "id": "4,1"
        }, {
          "type": "comment",
          "id": "6,1"
        }]
      }
    }
  }],
  "included": [{
    "type": "comment",
    "id": "4,1",
    "attributes": {
      "body": "OMG, cool project!"
    }
  }, {
    "type": "comment",
    "id": "6,1",
    "attributes": {
      "body": "Yeah, cool project!"
    }
  }]
}
```

**Comment by chamini2** [comment]
I also notice I could have a `_id` column that just does loads this format before sending it in. What do you think?

**Comment by danivek** [comment]
@chamini2, Interesting addition 👍
json-api-serializer already does a lot of transformations on data, so why not on `id`.

a PR is welcome !

Thanks

**Comment by chamini2** [comment]
Hey, @danivek, I was thinking about this and what thing that _worries_ me is how the `deserialize` would work?

**Comment by danivek** [comment]
@chamini2 You're right, `deserialize` needs to have an utility function to `unconvertId`. It could be also useful even if `id` is defined as a key for id on data.

E.g. if id on input data is an `int`, to be spec compliant, `json-api-serialiser` serialize id with `toString()`.
```javascript
Serializer.register('article', {
  id: '_id', 
  }
});

const jsonapi_payload = Serializer.serialize('article', {'_id': 123 });
```
```json
jsonapi_payload = {
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "article",
    "id": "123" // serialized with toString()
  }
}
```

But when we deserialize it, it's not possible actually to convert back to `int`.
```javascript
Serializer.deserialize('article', jsonapi_payload);
```
```json
{
 "_id": "123"
}
```

So, adding a function to unconvertId is not surprising.

**Comment by chamini2** [comment]
Ok, what about:

```ts
Serializer.register('coment', {
  id: {
    serialize(attributes) { return `${attributes.user_id},${attributes.article_id}`; },
    deserialize(id) {
      const [user_id, article_id] = id.split(',');
      return { user_id, article_id };
    }
  }
})
```

Or could be

```ts
Serializer.register('coment', {
  id: {
    serialize(attributes) { return `${attributes.user_id},${attributes.article_id}`; },
    deserialize(id, attributes) {
      const [user_id, article_id] = id.split(',');
      attributes.user_id = user_id;
      attributes.article_id = article_id;
      return attributes;
    }
  }
})
```

I'm not sure which is better and why. I would really like your input and think about well before making a decision.

**Comment by danivek** [comment]
Something like this is fine for me:

```javascript
Serializer.register('coment', {
  id: {
    serialize(data) { // data looks like {"user_id": "1", "article_id": "2", ... }
      return `${data.user_id},${data.article_id}`; // should return a string
    },
    deserialize(data) { // data looks like {"type": "coment", "id": "1,2", attributes: { ... }}
      const [user_id, article_id] = data.id.split(',');
      return { user_id, article_id }; // Should return an object wich will be assign to deserialized data
    }
  }
})
```

**Comment by chamini2** [comment]
Cool!

**Comment by mattii** [comment]
Nice addition! I just solved a similar problem with a composite key just by adding a virtual field to an objection.js model. But having it in the serializer is good approach, too.

**Comment by nrcmkoh** [comment]
Is this feature supported? When I tried the above, I am getting the following error:

> "ValidationError: child \"id\" fails because [\"id\" must be a string]"

**Comment by danivek** [comment]
Not supported yet... nobody is working on it.
 PR is welcome !
