### ISSUE TITLE
Duplicate type + id in included, but different data.

### ISSUE THREAD

**Issue by wesselvdv** [danivek/json-api-serializer#39]
I am using this lib to serialize complex objects that might be referencing the same type, but that referenced object might not necessarily have the same attributes each time it's referenced.

Example:

```typescript
const obj = {
  tenant: {
    id: '2',
    property: {
      id: '1',
      street: 'whjatever a', 
      place: 'exaplmecity',
    },
  },
  landlord: {
    id: '3',
    property: {
      id: '1',
      street: 'whjatever a', 
      place: 'exaplmecity', 
      lease: 'test',
    },
  },
};
```

In the above the property is referenced multiple times, but because each time it's referenced, the data usage is different, so not all attributes are required. When the above is serialized it'll include the property twice in included because it's different. I know how to fix it afterwards, but I would love to just be able to flick a switch on json-api-serializer to indicate that I would like it to pro-actively merge the attributes of objects that are of the same type & have the same id. 

I do realize that the links might be different due to the relations being different.

**Comment by danivek** [comment]
Hi @wesselvdv,

Thanks for your work.
This library has the responsability to serialize a data to be JSONAPI spec compliant, and to deserialize this JSONAPI payload back to original data. 

E.g For this input data with 3 objects :
```javascript
[{
    id: '1',
    body: 'test body 1',
  }, {
    id: '2',
    body: 'test body 2',
  }, {
    id: '1',
    body: 'test body 1',
    additional: 'test additional 2',
  }];
```
After serializing, you will have an array of 2 objects.

How can the library will convert it back to original data (with 3 objects) ?

**Comment by wesselvdv** [comment]
The issue that I am facing is that those 3 objects are actually two objects. Where the objects that have the same id are the same entity, but one has more information loaded than the other. Hence the fact that I want them to be combined before they are sent off to the client.

I completely understand that this is a trivial example where one might easily correct that situation beforehand, but I have deeply nested objects with complex relations that are harder to recursively deduplicate, and/or merge.

**Comment by danivek** [comment]
If we add a transform option function to transform each record before the serialization on serializeData. Can that match your specific case ?

**Comment by wesselvdv** [comment]
Hmm, that could work if the callback is provided type, id, and the obj itself. It would be awesome if we could also customize the deduplication function. Not sure if that one’s running only running on included?

**Comment by mattii** [comment]
Just joining in to give another opinion to the mix:
I think this shouldn't be part of this library, but it should be done before or after the serialization. Checking every data item against each other for uniqueness by doing a deep-comparison does not scale well. It's already happening for *included* resources, which is necessary, since it's quite normal for nested data-relations to contain redundant data.

But your case seems to be a really rare edge-case. And since there's a workaround by merging duplicates in `data` after or before the serialization, I wouldn't add this complexity and probably negative performance-impact to this library.

**Comment by danivek** [comment]
I agree with @mattii, I was already not very convinced to add it for complexity reasons for a very specific need.

**Comment by wesselvdv** [comment]
I did indeed do what you suggested. Funny thing is that for me incorporating this into api-serializer somehow is more efficient than iterating over the list afterwards. I do agree with both of you, my case is rather edgy. 

Closing, :-).
