### ISSUE TITLE
Deserialize async?

### ISSUE THREAD

**Issue by honestserpent** [danivek/json-api-serializer#46]
I see there is `serializeAsync` but I don't see `deserializeAsync`.. Is this wanted? Am I missing something?

**Comment by danivek** [comment]
It's a missing feature that I wanted to plan for a long time. I did not take the time to work on it because no one asked for it. It seems like it's the right time to do it :wink:

PRs are welcome if you want to work on it.

**Comment by honestserpent** [comment]
I'd love to but I actually never jumped into an open source project before. Maybe this is the right time? I'm not a huge expert, so I may mess up a lot. I'd like to contribute but I need some guidance on how to start.. I kind of ashamed of this LOL

**Comment by danivek** [comment]
`Async` feature for `serialize` or `deserialize` is only useful if you deal with huge array of items. It allows you to have non blocking process on iterating over items thank to stream feature. 

For `serialize` or `deserialize` a single item it's not really do non blocking code.

Yes, you can give a look to the `serializeAsync` function.
