### ISSUE TITLE
Acceptance of malformed relationships

### ISSUE THREAD

**Issue by chamini2** [danivek/json-api-serializer#49]
I noticed that in 62b73867b272a2a93f661e1122fca733c2624d9b you are handling malformed relationships by ignoring them. This seems to me a debatable thing to do, since maybe we should be warning the user of the malformed data, rather than ignoring it.

I don't ask for us to check if it's malformed and throw on it, what I would suggest is not check for this at all. JSON API specifies a very clear payload format, so if it is not followed, it's understandable that this package would not work correctly.

What I am trying to say is, why not make the code __easier__ to maintain by accounting for less cases? Maybe I can remove this specific check in #48.

**Comment by danivek** [comment]
I accepted your PR too fast...

I totally agree with you. The best thing to do here is to remove this specific check.

**Comment by chamini2** [comment]
Great, @danivek, I left a comment: https://github.com/danivek/json-api-serializer/commit/4662768e6d8dc4913eb0bd79be1a9a9c34a61954#r27962123
