### ISSUE TITLE
dynamic type

### ISSUE THREAD

**Issue by jamesdixon** [danivek/json-api-serializer#54]
Hi there,

I can see that it's possible to change the type dynamically by passing in a configuration to the serializer itself. Is this possible with relationships?

My use case is that I have a `campaign` model that has a relationship `recipients`. These `recipients` can be of type `staff` or `customer`. 

Is this possible with the current implementation?

Thanks!

**Comment by danivek** [comment]
Hi,

Dynamic relationships are not currently possible. But I don't see any particular problems of implementing it.

**Comment by jamesdixon** [comment]
@danivek thanks. I'll submit a PR for this as soon as I get some time. Cheers

**Comment by jamesdixon** [comment]
@danivek oh wow, just saw that you had submitted a PR for this. Thanks!

**Comment by danivek** [comment]
@jamesdixon 😉. Can you give it a try and give me a feedback ? Thanks

**Comment by jamesdixon** [comment]
Will do!

**Comment by jamesdixon** [comment]
@danivek sorry for the delay on testing this!

Is it possible to allow the function access to the entire record? Unfortunately, the `id` doesn't give me enough information to set the type dynamically.

For example, my `campaign` record has a `type` field, which can be either `staff` or `customer`. That field is what I'd like to use in order to set the `type` property on the response.

Thanks!

**Comment by jamesdixon** [comment]
@danivek wanted to see if you had any thoughts on the above? Thank you!

**Comment by danivek** [comment]
@jamesdixon you’re right ! I will change this to allow the entire record to be passed to the type resolver function.

Thank you for your feedback !

**Comment by jamesdixon** [comment]
Thanks, @danivek! Much appreciated 👍

**Comment by danivek** [comment]
Now the type resolver function has 2 arguments `function(relationshipData, data) { ... }`
Can you give it a try ? 

Thanks @jamesdixon
