### ISSUE TITLE
Every resource object must contain an id member of type string

### ISSUE THREAD

**Issue by dynamiccast** [danivek/json-api-serializer#6]
Hi,

JSON API specification requires resource object to contain an `id` member **of type string**. http://jsonapi.org/format/#document-resource-objects.

*json-api-serializer* simply copies provided unique identifier here : https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L96 but **do not care** about the type.
In my case, I am trying to serialize data coming out of an ORM where SQL tables' primary keys are set to auto increment, resulting in unique identifiers of type *number*.

Do you think this is the role of *json-api-serializer* to try to call `toString()` in case given identifier is not of type string ? As this is required by the spec, I would expect a serializer to do it.

Any thoughts ?

**Comment by danivek** [comment]
Hi, 

You are right, the serializer should return string for the id attributes.
