### ISSUE TITLE
Should be able to return "Resource Identifier Objects"  

### ISSUE THREAD

**Issue by dimisus** [danivek/json-api-serializer#62]
I try to return a resource identifier object of an entity and to do so I tried to whitelist the 'id' only or to serialize data where data = { id }.

I always end up with the attributes object being empty `attributes: {}` 

Shouldn't there be an option to deactivate attributes or any way to represent the resource identifier only?

**Comment by dimisus** [comment]
I think what is needed is a flag... something like `onlyResourceIdentifiers`...  I will try to create a pull request asap.

**Comment by danivek** [comment]
@dimisus, You are right, there is no reason to keep empty `attributes` property. I will add a check for empty `attributes` property.

**Comment by dimisus** [comment]
Okay, cool. Thank you.

**Comment by danivek** [comment]
Fixed in v1.14.1
