### ISSUE TITLE
Replace Joi with AJV

### ISSUE THREAD

**Issue by faustbrian** [danivek/json-api-serializer#63]
https://github.com/hapijs/joi/issues/1601#issuecomment-431677851

Is Joi set in stone or would a PR to replace Joi with AJV be accepted?

**Comment by danivek** [comment]
A schema validator (Joi here) just serves to validate options on type registration. It's only to have prettier errors if developer set a wrong object.

`serialize` and `deserialize` functions don't use schema validation, so in term of performance, moving to AJV will not have impact on these functions.

**Comment by danivek** [comment]
I think that the best solution here, is to have an internal validator to ensure that input is correct instead of having a dependency to a whatever external schema validator.

**Comment by faustbrian** [comment]
One place that I noticed that is slow because of Joi while doing some testing is https://github.com/danivek/json-api-serializer/blob/master/lib/JSONAPISerializer.js#L417.

If you use the `serializeError` method and have a lot of traffic that results in errors, like a 422, it can take a hit on performance. Overall the use of Joi is fine but I am avoiding the use of `serializeError` due to that.

An internal validator would be an alternative but it would be questionable if it will be faster then AJV/JSON schema.

**Comment by lupestro** [comment]
While using Joi, it might not hurt to upgrade from 12.0.0 to 14.3.1 and avoid the dependency deprecation warnings. There were some marginal breaking changes to check your usage against, though...
