### ISSUE TITLE
Client side deserialization

### ISSUE THREAD

**Issue by asalisaf** [danivek/json-api-serializer#64]
Hello and thanks for your package
I have two question:
1. Can this package be used as client side serializer/deserialzer?
2. If yes does it handle included part?
Your help would be appreciated

**Comment by stefanvanherwijnen** [comment]
Maybe this will help you:
https://github.com/danivek/json-api-serializer/issues/65

I see no reason why it would not work on a client.

**Comment by danivek** [comment]
Add browser support on v2.5.0
