### ISSUE TITLE
Id always serialized as string

### ISSUE THREAD

**Issue by Hardsix** [danivek/json-api-serializer#72]
I'm using PostgreSQL and my ids are integers (doesn't quite matter what they are, they should be able to be any data type), and I wish to avoid having to do conversions because the frontend receives string ids and then naturally sends them back that way in the body.

json-api-serializer doesn't seem to have an option to preserve id type, so I have to work around this issue, which I don't like.

Simple example:
I'm generating asset urls based on some context data which is passed through the body. The web has an `accountId` that's a string because this serializer returns it as one, and when I receive the id in the context, I have to parse it manually.

**Comment by danivek** [comment]
According to the JSON:API specification https://jsonapi.org/format/#document-resource-object-identification, The values of the id and type members **MUST** be strings.

**Comment by Hardsix** [comment]
Hi, sorry for the confusion then, and thank you for the prompt response! 👍
