### ISSUE TITLE
bug: When installed in Angular project, it throws error since it is searching for `fs`

### ISSUE THREAD

**Issue by diosney** [danivek/json-api-serializer#87]
Which seems to be an error with the `30-seconds-of-code` dependency requiring `fs`, which doesn't exists.

```
ERROR in ./node_modules/30-seconds-of-code/dist/_30s.esm.js
Module not found: Error: Can't resolve 'fs' in '/home/user/some-project/node_modules/30-seconds-of-code/dist'
```

**Comment by diosney** [comment]
Sorry, it seems that this library isn't mean for client-side, which is a boomer, to be frank, since I wanted to use the same library on both sides (I'm currently using it on server side).

**Comment by danivek** [comment]
@diosney I’m working on this. See PR #75. I need feedback. Can you try it ?
